### ISSUE TITLE
setup.py still installing EZID 0.3

### ISSUE THREAD

**Issue by ngeraci** [ucldc/pynux#23]
When installing the most recent version of pynux in a clean Python 3 environment using `python setup.py install`, I'm still getting EZID 0.3 installed instead of 0.4.2. 

`pip install https://github.com/ucldc/pynux/tarball/master --upgrade` does correctly install EZID 0.4.2.

**Comment by tingletech** [comment]
yes, this is true -- `python setup.py install` won't work.

I have not been able to take over Mark's code on pypi since he passed.

**Comment by ngeraci** [comment]
thank you for updating the docs!
