### ISSUE TITLE
nxid NameError (unicode type)

### ISSUE THREAD

**Issue by ngeraci** [ucldc/pynux#24]
In a Python 3 environment, when I run `nxid` for a Nuxeo object that has a value in the "Creator" field, I get the following error:
```
line 214, in <genexpr>
    creator = '; '.join(list(unicode(c.get('name')) for c in creator_list))
NameError: name 'unicode' is not defined
```
Since `str` type replaced `unicode` type in Python 3, would just changing the `unicode` to `str` here in line 214 fix this? Or would that cause other issues for Python 2 users?

**Comment by tingletech** [comment]
ah, thanks, it is hard for me to test this since I don't really want to write to EZID.

I think we need something like this for now https://stackoverflow.com/a/53286631/1763984
